// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=internal/mocks/mock_contracts.go -package=mocks OrderCache OrderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	internal "order-service/internal"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderCache is a mock of OrderCache interface.
type MockOrderCache struct {
	ctrl     *gomock.Controller
	recorder *MockOrderCacheMockRecorder
	isgomock struct{}
}

// MockOrderCacheMockRecorder is the mock recorder for MockOrderCache.
type MockOrderCacheMockRecorder struct {
	mock *MockOrderCache
}

// NewMockOrderCache creates a new mock instance.
func NewMockOrderCache(ctrl *gomock.Controller) *MockOrderCache {
	mock := &MockOrderCache{ctrl: ctrl}
	mock.recorder = &MockOrderCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderCache) EXPECT() *MockOrderCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOrderCache) Delete(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", arg0)
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderCacheMockRecorder) Delete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderCache)(nil).Delete), arg0)
}

// DeleteAllItems mocks base method.
func (m *MockOrderCache) DeleteAllItems() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteAllItems")
}

// DeleteAllItems indicates an expected call of DeleteAllItems.
func (mr *MockOrderCacheMockRecorder) DeleteAllItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllItems", reflect.TypeOf((*MockOrderCache)(nil).DeleteAllItems))
}

// Get mocks base method.
func (m *MockOrderCache) Get(arg0 string) (*internal.Order, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*internal.Order)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderCacheMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderCache)(nil).Get), arg0)
}

// Set mocks base method.
func (m *MockOrderCache) Set(arg0 *internal.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0)
}

// Set indicates an expected call of Set.
func (mr *MockOrderCacheMockRecorder) Set(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockOrderCache)(nil).Set), arg0)
}

// Warm mocks base method.
func (m *MockOrderCache) Warm(arg0 []*internal.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warm", arg0)
}

// Warm indicates an expected call of Warm.
func (mr *MockOrderCacheMockRecorder) Warm(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warm", reflect.TypeOf((*MockOrderCache)(nil).Warm), arg0)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOrderRepository) Get(arg0 context.Context, arg1 string) (*internal.Order, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*internal.Order)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockOrderRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderRepository)(nil).Get), arg0, arg1)
}

// ListRecentIDs mocks base method.
func (m *MockOrderRepository) ListRecentIDs(arg0 context.Context, arg1 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentIDs", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentIDs indicates an expected call of ListRecentIDs.
func (mr *MockOrderRepositoryMockRecorder) ListRecentIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentIDs", reflect.TypeOf((*MockOrderRepository)(nil).ListRecentIDs), arg0, arg1)
}

// LoadRecent mocks base method.
func (m *MockOrderRepository) LoadRecent(arg0 context.Context, arg1 int) ([]*internal.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRecent", arg0, arg1)
	ret0, _ := ret[0].([]*internal.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRecent indicates an expected call of LoadRecent.
func (mr *MockOrderRepositoryMockRecorder) LoadRecent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRecent", reflect.TypeOf((*MockOrderRepository)(nil).LoadRecent), arg0, arg1)
}

// Upsert mocks base method.
func (m *MockOrderRepository) Upsert(arg0 context.Context, arg1 *internal.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockOrderRepositoryMockRecorder) Upsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockOrderRepository)(nil).Upsert), arg0, arg1)
}
